const homeText = {
    en: {
        newsletterTitle: "Want to follow the ministry of Dr. G. W. Arthur?",
        newsletterSubtext: "Subscribe to the newsletter for messages, audio, videos, and updates on his ministry right in your inbox.",
        newsletterNameInput: "Name",
        newsletterEmailInput: "Email",
        newsletterSubmit: "Submit",
        readMoreTitle: "See What God Has Been Up to in the Ministry",
        readMoreSubtext: "Discover stories of transformation, powerful testimonies, and awe-inspiring events that highlight the remarkable work of God. Get ready to be inspired by the incredible journey we're on!",
        readMoreButton: "Read More",

        latestTitle: "Watch the latest Video Messages",
        latestSubtext: "Watch videos that will help you become more like Christ in every way. These messages are guides, showing you how to grow spiritually and attain the full measure and stature of Christ.",
        latestButton: "Start Watching",

        listenTitle: "Listen to the latest Audio Messages",
        listenSubtext: "Get ready to hit play on audio messages from Dr. G. W. Arthur It's not just a listen; it's a spiritual experience. Join the uplifting journey, and let the power of God's words change your soul.",
        listenButton: "Listen to more",

        socialsTitle: "Connect to God's Work!",
        socialsSubtext: "Follow Dr. G. W. Arthur on Facebook, Instagram, and Twitter. Together, we'll build a community for growing into the consciousness of Christ and his finished work.",

        questionsTitle: "Got Burning Questions?",
        questionsSubtext: "We've Got the Answers! Fire away using the form below. Whether it's a prayer request or just a friendly shout-out, we're here for you! Your connection is what makes the journey exciting.",
        questionsNameInput: "What is your name",
        questionsQuestionInput: "What question is on your heart",
        questionsButton: "Ask Now",


        platformsTitle: "Listen to Dr. G. W. Arthur on all platforms now",
        platformsButton: "Listen Now",

        footerTitle: "About Dr. G. W. Arthur",
        footerInfo: "Dr. G. W. Arthur is the shepherd and driving force behind George Wilfred Arthur Ministries (G. W. Arthur Ministries). With a profound commitment to the restoration of God's Word, Rev. George brings a unique blend of passion, wisdom, and love to his ministry.",
        footerLinks: "Links",
        footerHome: "Home",
        footerBiography: "Biography",
        footerContact: "Contact",
        footerExternalLinks: "External Links",
        footerGallery: "From The Gallery"
    },
    fr: {
        "newsletterTitle": "Voulez-vous suivre le ministère du Dr. G. W. Arthur?",
        "newsletterSubtext": "Abonnez-vous à la newsletter pour recevoir des messages, des audios, des vidéos et des mises à jour sur son ministère directement dans votre boîte de réception.",
        "newsletterNameInput": "Nom",
        "newsletterEmailInput": "Email",
        "newsletterSubmit": "Soumettre",
        "readMoreTitle": "Voir ce que Dieu a fait dans le ministère",
        "readMoreSubtext": "Découvrez des histoires de transformation, des témoignages puissants et des événements impressionnants qui mettent en lumière le travail remarquable de Dieu. Préparez-vous à être inspiré par le voyage incroyable dans lequel nous sommes engagés!",
        "readMoreButton": "Lire plus",
        "latestTitle": "Regardez les derniers messages vidéo",
        "latestSubtext": "Regardez des vidéos qui vous aideront à devenir plus comme Jésus de toutes les manières. Ces messages sont des guides, vous montrant comment grandir spirituellement et atteindre la pleine mesure et la stature de Jésus.",
        "latestButton": "Commencer à regarder",
        "listenTitle": "Écoutez les derniers messages audio",
        "listenSubtext": "Préparez-vous à appuyer sur play sur les messages audio du Dr. G. W. Arthur. Ce n'est pas seulement un écoute; c'est une expérience spirituelle. Rejoignez le voyage encourageant, et laissez la puissance des mots de Dieu changer votre âme.",
        "listenButton": "Écouter davantage",
        "socialsTitle": "Connectez-vous à l'œuvre de Dieu!",
        "socialsSubtext": "Suivez le Dr. G. W. Arthur sur Facebook, Instagram et Twitter. Ensemble, nous construirons une communauté pour grandir dans la conscience de Jésus et son œuvre achevée.",
        "questionsTitle": "Des questions brûlantes?",
        "questionsSubtext": "Nous avons les réponses! Faites-leur savoir en utilisant le formulaire ci-dessous. Que ce soit une demande de prière ou simplement un cri amical, nous sommes là pour vous! Votre connexion est ce qui rend le voyage excitant.",
        "questionsNameInput": "Quel est votre nom",
        "questionsQuestionInput": "Quelle question est sur votre cœur",
        "questionsButton": "Poser maintenant",
        "platformsTitle": "Écoutez le Dr. G. W. Arthur sur toutes les plateformes maintenant",
        "platformsButton": "Écouter maintenant",
        "footerTitle": "À propos du Dr. G. W. Arthur",
        "footerInfo": "Le Dr. G. W. Arthur est le pasteur et la force motrice derrière les Ministères George Wilfred Arthur (Ministères G. W. Arthur). Avec un engagement profond pour la restauration du mot de Dieu, le Rév. George apporte une combinaison unique de passion, de sagesse et d'amour à son ministère.",
        "footerLinks": "Liens",
        "footerHome": "Accueil",
        "footerBiography": "Biographie",
        "footerContact": "Contact",
        "footerExternalLinks": "Liens externes",
        "footerGallery": "De la galerie"
    },
    es: {
        "newsletterTitle": "¿Quieres seguir el ministerio del Dr. G. W. Arthur?",
        "newsletterSubtext": "Suscríbete al boletín para recibir mensajes, audios, videos y actualizaciones sobre su ministerio directamente en tu bandeja de entrada.",
        "newsletterNameInput": "Nombre",
        "newsletterEmailInput": "Email",
        "newsletterSubmit": "Enviar",
        "readMoreTitle": "Ve lo que Dios ha estado haciendo en el ministerio",
        "readMoreSubtext": "Descubre historias de transformación, testimonios poderosos y eventos impresionantes que destacan el trabajo notable de Dios. ¡Prepárate para inspirarte con el increíble viaje en el que estamos!",
        "readMoreButton": "Leer más",
        "latestTitle": "Mira los últimos mensajes de video",
        "latestSubtext": "Mira videos que te ayudarán a ser más como Cristo de todas las maneras. Estos mensajes son guías, mostrándote cómo crecer espiritualmente y alcanzar la plena medida y la estatura de Cristo.",
        "latestButton": "Escucha más",
        "listenTitle": "Escucha los últimos mensajes de audio",
        "listenSubtext": "Prepárate para presionar play en los mensajes de audio del Dr. G. W. Arthur. No es solo una escucha; es una experiencia espiritual. Únete al viaje inspirador y deja que la poderosa voz de Dios cambie tu alma.",
        "listenButton": "Empezar a escuchar",
        "socialsTitle": "¡Conéctate al trabajo de Dios!",
        "socialsSubtext": "Sigue al Dr. G. W. Arthur en Facebook, Instagram y Twitter. Juntos, construiremos una comunidad para crecer en la conciencia de Cristo y su obra completada.",
        "questionsTitle": "¿Tienes preguntas ardientes?",
        "questionsSubtext": "¡Tenemos las respuestas! Dispara usando el formulario de abajo. Ya sea una solicitud de oración o simplemente un grito amigable, ¡estamos aquí para ti! Tu conexión es lo que hace que el viaje sea emocionante.",
        "questionsNameInput": "¿Cuál es tu nombre?",
        "questionsQuestionInput": "¿Qué pregunta está en tu corazón?",
        "questionsButton": "Hacer ahora",
        "platformsTitle": "¡Escucha al Dr. G. W. Arthur en todas las plataformas ahora!",
        "platformsButton": "Escuchar ahora",
        "footerTitle": "Sobre el Dr. G. W. Arthur",
        "footerInfo": "El Dr. G. W. Arthur es el pastor y la fuerza motriz detrás de los Ministerios George Wilfred Arthur (Ministerios G. W. Arthur). Con un compromiso profundo con la restauración de la Palabra de Dios, el Rev. George aporta una mezcla única de pasión, sabiduría y amor a su ministerio.",
        "footerLinks": "Enlaces",
        "footerHome": "Inicio",
        "footerBiography": "Biografía",
        "footerContact": "Contacto",
        "footerExternalLinks": "Enlaces externos",
        "footerGallery": "De la galería"
    },
    pt: {
        "newsletterTitle": "Quer seguir o ministério do Dr. G. W. Arthur?",
        "newsletterSubtext": "Inscreva-se no boletim para receber mensagens, áudios, vídeos e atualizações sobre seu ministério diretamente na sua caixa de entrada.",
        "newsletterNameInput": "Nome",
        "newsletterEmailInput": "Email",
        "newsletterSubmit": "Enviar",
        "readMoreTitle": "Veja o que Deus tem feito no ministério",
        "readMoreSubtext": "Descubra histórias de transformação, testemunhos poderosos e eventos impressionantes que destacam o trabalho notável de Deus. Prepare-se para ser inspirado pela incrível jornada em que estamos!",
        "readMoreButton": "Ler mais",
        "latestTitle": "Assista às últimas mensagens em vídeo",
        "latestSubtext": "Assista a vídeos que ajudarão você a se tornar mais como Cristo de todas as maneiras. Essas mensagens são guias, mostrando como crescer espiritualmente e alcançar a plena medida e a estatura de Cristo.",
        "latestButton": "Ouça mais",
        "listenTitle": "Ouça as últimas mensagens em áudio",
        "listenSubtext": "Prepare-se para pressionar play nas mensagens de áudio do Dr. G. W. Arthur. Não é apenas uma ouvir; é uma experiência espiritual. Junte-se à jornada inspiradora e deixe a força das palavras de Deus mudar sua alma.",
        "listenButton": "Começar a ouvir",
        "socialsTitle": "Conecte-se ao trabalho de Deus!",
        "socialsSubtext": "Siga o Dr. G. W. Arthur no Facebook, Instagram e Twitter. Juntos, construiremos uma comunidade para crescer na consciência de Cristo e em Sua obra concluída.",
        "questionsTitle": "Tem perguntas ardentes?",
        "questionsSubtext": "Temos as respostas! Dispare usando o formulário abaixo. Seja uma solicitação de oração ou apenas um grito amigável, estamos aqui para você! Sua conexão é o que torna a jornada emocionante.",
        "questionsNameInput": "Qual é o seu nome",
        "questionsQuestionInput": "Qual pergunta está no seu coração",
        "questionsButton": "Perguntar agora",
        "platformsTitle": "Ouça o Dr. G. W. Arthur em todas as plataformas agora",
        "platformsButton": "Ouvir agora",
        "footerTitle": "Sobre o Dr. G. W. Arthur",
        "footerInfo": "O Dr. G. W. Arthur é o pastor e a força motriz por trás dos Ministérios George Wilfred Arthur (Ministérios G. W. Arthur). Com um compromisso profundo com a restauração da Palavra de Deus, o Rev. George traz uma mistura única de paixão, sabedoria e amor para seu ministério.",
        "footerLinks": "Links",
        "footerHome": "Início",
        "footerBiography": "Biografia",
        "footerContact": "Contato",
        "footerExternalLinks": "Links externos",
        "footerGallery": "Da galeria"
    },
    ch: {
        "newsletterTitle": "想要跟随Dr. G. W. Arthur的神职吗？",
        "newsletterSubtext": "订阅通讯，直接在您的收件箱中获取消息、音频、视频和关于他的神职的更新。",
        "newsletterNameInput": "姓名",
        "newsletterEmailInput": "电子邮件",
        "newsletterSubmit": "提交",
        "readMoreTitle": "看看神在神职中做了什么",
        "readMoreSubtext": "发现转变的故事、强大的见证和令人震撼的事件，突显神的显著工作。准备好被我们正在经历的不可思议旅程所启发吧！",
        "readMoreButton": "阅读更多",
        "latestTitle": "观看最新的视频信息",
        "latestSubtext": "观看视频，帮助你在各方面更像基督。这些信息是指南，向你展示如何精神成长和达到基督的完整量和身份。",
        "latestButton": "开始观看",
        "listenTitle": "听最新的音频信息",
        "listenSubtext": "准备在Dr. G. W. Arthur的音频信息上按下播放。这不仅仅是听；这是一种精神体验。加入这个鼓舞人心的旅程，让神的话语改变你的灵魂。",
        "listenButton": "听更多",
        "socialsTitle": "连接到神的工作！",
        "socialsSubtext": "在Facebook、Instagram和Twitter上关注Dr. G. W. Arthur。我们一起建立一个社区，共同成长为基督的意识和完成的工作。",
        "questionsTitle": "有燃烧的问题吗？",
        "questionsSubtext": "我们有答案！使用下面的表格随时提问。无论是祈祷请求还是仅仅是友好的呼喊，我们都在这里为你服务！你的联系是使旅程变得激动人心的原因。",
        "questionsNameInput": "你的名字是什么",
        "questionsQuestionInput": "你心中的问题是什么",
        "questionsButton": "现在提问",
        "platformsTitle": "现在就在所有平台上听Dr. G. W. Arthur",
        "platformsButton": "现在听",
        "footerTitle": "关于Dr. G. W. Arthur",
        "footerInfo": "Dr. G. W. Arthur是George Wilfred Arthur Ministries（G. W. Arthur Ministries）的牧师和驱动力。他对神的话的复兴有着深深的承诺，Rev. George为他的神职带来了独特的热情、智慧和爱。",
        "footerLinks": "链接",
        "footerHome": "主页",
        "footerBiography": "传记",
        "footerContact": "联系方式",
        "footerExternalLinks": "外部链接",
        "footerGallery": "画廊"
    },
}

export default homeText